[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_BASE_URL = "https://uber-poz1.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
